# default prompt for all math benchmarks (e.g. gsm8k, math)


system: ""

user: |-
  You are an advanced mathematical reasoning assistant. Your task is to **revise the given solution** by **introducing exactly 1 intentional mistake and naturally correcting them during the reasoning process** while keeping the final answer correct.


  please start with your modified output with "Solution"
  please make sure finish the solution with **Final Answer**
  \[ \boxed{{YOUR ANSWER}} \] 

  ### **Self-Correction Definition**:
  Self-correction means identifying an error and actively correcting it, realizing a mistake, and adjusting calculations. 

  - **How to introduce self-corrections naturally**:
    - The mistake should **not be immediately obvious**—it should be discovered through reasoning.
    - The correction should **flow naturally** in the thought process, as if the author notices it while solving.
    - The author may hesitate, second-guess, and re-evaluate before making a correction.

  - **Example self-correction phrases**:
    - "Wait, something feels off here... let me check."
    - "Oh! I think I see the mistake..."
    - "Hold on, I might have miscalculated this part."
    - "Let’s go back and check this—something doesn’t look right."

  ---

  ### **Instructions**:
  1. **Modify the given solution** by **introducing 1 mistakes*, but make them subtle and realistic.
  2. **Do not list mistakes separately**—instead, make the author realize and correct them **naturally while solving the problem**.
  3. **Ensure the author notices mistakes through logical reasoning** (e.g., unexpected results, inconsistencies, or rechecking).
  4. **Self-corrections should be embedded seamlessly**, making the reasoning feel more human and exploratory.
  5. **Maintain the original logic and ensure the final answer remains correct**.


  Most important: Modify the given solution** by **introducing 1 mistake**, but make them subtle and realistic.
  Please avoid using phrases like "let us introduce a few mistakes," "we will intentionally add some errors," or "for demonstration purposes, 
  we will insert some mistakes," and ensure the wording sounds natural.
  
  Now I will give you the following solution, please Modify and Improve:
  {output}