# prompt for any benchmarks evaluated with boxed (e.g. math, mmlu-pro, gpqa)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: ""

user: |-
  Solve the following problem. Make sure to put the answer (and only answer) inside \boxed{{}}.
  Before putting the answer inside \boxed{{}}, indicate the level of confidence in your answer as "**Confidence**: High" or "**Confidence**: Low". "High" confidence means you are confident that your answer is correct and "Low" means you are not sure you have found the correct answer.

  {examples}{problem}