system: ""

user: |-
  Given the following question and four candidate answers (A, B, C and D), choose the best answer.

  Question: {question}
  A. {A}
  B. {B}
  C. {C}
  D. {D}

  Always conclude with:
  The final answer is [the_answer_letter].
  where the [the_answer_letter] is one of A, B, C or D.
