# default prompt for all multi-choice benchmarks (e.g. mmlu)

system: ""

user: |-
   Please help me to extract clear and concise problem statements from mathematical forums. Use the following guidelines:

    Identify Distinct Questions:
       Analyze the post to determine if it contains one or more distinct questions.
       If there is only one question, output it as a single, standalone sentence without numbering
       If there are multiple questions, format them as a sequentially numbered list (e.g., Question 1, Question 2, etc.).
    
    Ensure Clarity and Focus:
       Rephrase each question concisely, ensuring it captures the essence of the inquiry.
       Remove redundant context, personal commentary, anecdotes, or unrelated information.
       Preserve technical terms and necessary mathematical or technical details.
    
    Handle Non-Question Posts:
       If the post does not include any clear question or problem, simply output: "No problem identified."
    
    Here are a few examples. 
    Example 1

    "Question 1:
    A tetrahedron has four vertices. We can label each vertex by one of the four digits: 1,2,3,4. How many non-congruent ways are there to assign a different digit to each vertex of a tetrahedron? Tetrahedra are considered congruent through rotation. 
    Reflections are considered different. I'm wondering how I could approach a problem like this. I started off with 4! and then divided by 4 to take out the rotation aspect. Now I am stuck.
    Note: I'd rather not do case work because I'm sure the test writers could have easily used an icosahedron, or something equally lengthy.
    Another Question along the same lines:
    How many ways to color a cube using 6 colors, where each face has a unique color? Thanks"

    Output:
    "Question 1: How many non-congruent ways are there to assign a different digit to each vertex of a tetrahedron, considering rotations but treating reflections as different?
    Question 2: How many ways can a cube be colored using 6 colors, where each face has a unique color?"



    Example 2:
    Forum post:
    Countdown:\r\n\r\nWhat is the remainder of 8^6+7^7+6^8 is divided by 5?\r\n\r\n\r\nno calculator of course, paper isn't needed either, but sure
    No calculator of course, paper isn't needed either, but sure."

    Output:
    What is the remainder of 8^6+7^7+6^8 is divided by 5?

    Example 3:
    Forum post:
    "Yes! I completely agree with what you said. It's been a tough transition for me too, but we'll figure it out."

    Output:
    "No problem identified"


    Example 4:
    Forum post:
    Billy Bob has fourteen different pairs of socks in his drawer. They are just thrown around randomly in the drawer. Billy Bob once woke up in a hurry and had to get his socks quickly. 
    Without switching the light on, he pulled out enough socks to know that he had at least one pair, and then he ran out of the room. How many socks did Billy Bob pull out

    
    Output:
    Billy Bob has 14 different pairs of socks in his drawer, making 28 individual socks. Each sock in the drawer has a matching pair. The socks are mixed randomly. 
    In the dark, how many socks must Billy Bob pull out to ensure he has at least one complete matching pair?



    Example 5:
    Forum post:
    Reverend Jethro is making a pigpens and cowpens to contain his pigs and cows. If it takes 350 yards of fencing to make a circular pen 35 yards in diameter to hold his cows, 
    how many feet of fencing will it take to to make a circular pen with a 54-inch radius to hold his pigs?,
    
    Output:
    Reverend Jethro is making pigpens and cowpens to contain his pigs and cows. If it takes 350 yards of fencing to make a circular pen 35 yards in diameter to hold his cows, 
    how many feet of fencing will it take to make a circular pen with a 54-inch radius to hold his pigs?
    {problem}