# default prompt for all math benchmarks (e.g. gsm8k, math)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: ""

user: |-
  You are an advanced mathematical reasoning assistant. 

  Your goal is to make this response highly engaging, natural, and conversational.  
  The explanation should feel like a friendly discussion rather than a rigid math proof.

  Modify the following mathematical solution to be **natural, exploratory, and engaging**, as if a person were solving the problem step by step in real time.  
  Please always start the solution with **"Solution: "**  
  Please make sure the revised solution ends with **Final Answer**  
  
    \[
  \boxed{{YOUR ANSWER}}
  \]

  Guidelines for the response:

  1. **Make it feel like a real conversation**  
    - Use friendly, casual phrasing:
      - "Alright, let’s see what’s happening here."
      - "Hmm… interesting. What if we try this?"
    - Write as if explaining to a curious friend, not in a textbook style.

  2. **Think out loud, like a real person solving a problem**  
    - Include natural reasoning, such as:
      - "Let's check if this works..."
      - "Oh! That actually makes sense now!"
    - When switching strategies, narrate the process:
      - "This looks tricky. Maybe another approach works better?"

  3. **Make it exploratory—try different approaches before settling on a solution**  
    - Instead of jumping straight to the answer, test simple cases first.
    - Introduce trial and error:
      - "Let’s try plugging in \( x = 1 \) and see what happens."
      - "This almost works, but let’s tweak it."

  4. **Use relatable explanations and comparisons**  
    - Introduce metaphors where helpful:
      - "This part is like balancing a seesaw—both sides need to match."
      - "I always double-check my signs—small mistakes sneak in so easily!"

  5. **Ensure the final answer feels earned, not just stated**  
    - Instead of just saying *"Thus, the answer is..."* use:
      - "Alright, this checks out, so our final answer is..."
      - "That was a journey, but we got there! The final answer is..."
    - Always box the final answer:
    \[
    \boxed{{YOUR ANSWER}}
    \]

  ### **Additional Instructions to Encourage a Longer Response**:
  - **Explain each step in detail, including why it works and how it connects to the previous step.**  
  - **If possible, explore at least two different solution approaches before deciding on the best one.**  
  - **Provide intuitive explanations before diving into formal calculations.**  
  - **After solving, verify the answer using sample values or an alternative method.**  
  - **Consider real-world applications or historical context if relevant.**  
  - **Discuss any edge cases or special conditions that could affect the solution.**  

  
  
  **Original Problem:**
  {input}

  **AI-Generated Solution (to be improved):**
  {output}

  **Rewritten and Expanded Solution (Conversational, Engaging, and Detailed Style):**
  Output: