# default prompt for all math benchmarks (e.g. gsm8k, math)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: ""

user: |-
  You are an advanced mathematical reasoning assistant. Your task is to analyze a given mathematical solution and count occurrences of three reasoning patterns. 
  **Base your analysis on context and logical intent, not just keywords.**

  The final answer should be in the following format:
  Self-Checking	\boxed{{X}}
  Self-Correction \boxed{{Y}}
  Trial-and-Error	\boxed{{Z}}

  ### **Reasoning Categories**:

  1. **Self-Checking**: When the author verifies a step, checks a calculation, or confirms whether the approach satisfies given conditions.  
    - **Typical phrases**:  
      - "Wait, let me check..."  
      - "Let’s verify if this works..."  
      - "Before going further, let’s confirm..."  
      - "Now, let's check if this satisfies the given conditions."

  2. **Self-Correction**: When the author identifies an error and actively corrects it.  
    - **Typical phrases**:  
      - "Oh! I see the mistake..."  
      - "Wait, that seems incorrect..."  
      - "Let me recompute this..."  
      - "Maybe I made an error, let me fix that."

  3. **Trial-and-Error Thinking**: When the author experiments with different approaches, tests values, or adjusts methods.  
    - **Typical phrases**:  
      - "Let’s try plugging in..."  
      - "What if we try another approach?"  
      - "Maybe this method works better..."  
      - "Let’s test a few cases before proceeding."

  **⚠ Important:** Do not rely solely on keyword matching. Consider the **logical intent** behind each sentence to classify it correctly.

    ### **Instructions**:
  1. Read the entire mathematical solution carefully.
  2. Identify and count occurrences of **each reasoning pattern**.
  3. **Ensure that each instance truly fits the reasoning type** (do not just rely on keywords).
  4. **Provide a structured table summarizing the occurrences.**
  5. **Give 2-3 examples** from the text for each category, explaining why they fit.
  6. **Use LaTeX-style `\boxed{}` notation for the final counts in the table.**

  {examples}{generation}


  ### **Expected Output Format**
  The final answer should be in the following format:
  Self-Checking	\boxed
  Self-Correction	\boxed
  Trial-and-Error	\boxed

  Now I will give you the solution as below: