# default prompt for all math benchmarks (e.g. gsm8k, math)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: ""

user: |-
  I will give you a math problem and ask to solve it. Your goal is to write your thinking process as you approach this math problem. 
  Note that we are not that much interested in the final solution, but much more in the process that lead you to it. 
  Did you have references to other problems you solved before in your mind? Write that down. 
  Did you ponder upon which approach to take before doing derivations? Write that down. 
  Does your current approach look too complicated and you need to try something else? Say that and write down any alternative ideas you have. 
  Did you notice that something doesn't look good and you need to double check previous derivations for mistake? That's what we are looking for - write that down and correct the solution, but don't erase the mistake! 
  The more detailed this is, the better. In fact, if you know right away how to solve a problem, consider simulating some other plausible but incorrect approaches and writing that down, as a straightforward correct solution is not going to be useful for us.

  Here are a few more things to keep in mind
  Finish the solution with **Final Answer**
  \[ \boxed{{YOUR ANSWER}} \] 


  Don't use calculator or any other external tools. It's best if you don't even use a paper, but instead write everything directly in computer in latex. If you're not comfortable doing that, it's ok to write the solution on paper, but don't leave out any thoughts or derivations as you do it.
  E.g. if you had to go to another page and multiple two 4-digit numbers there, it's important that you carry it back to your solution, such that all arithmetical operations or equation simplifications that are there are easy to do in your head. E.g. instead of writing 680*389=264520 , 
  do it like this instead I need to multiply 680*389.
  680 * 400 = 272,000
  680 * (-11) = -7,480 (since 389 = 400 - 11)
  So, 272,000 - 7,480 = 264,520.
  You can be even more detailed if you'd like, more details are never harmful here.

  {examples}{problem}


  Please share your thinking process now. Remember: your goal is to write your thinking process as you approach this math problem. Note that we are not that much interested in the final solution, but much more in the process that lead you to it. 
  Did you have references to other problems you solved before in your mind? Write that down. Did you ponder upon which approach to take before doing derivations? Write that down. Does your current approach look too complicated and you need to try something else? 
  Say that and write down any alternative ideas you have. Did you notice that something doesn't look good and you need to double check previous derivations for mistake? That's what we are looking for - write that down and correct the solution, but don't erase the mistake! 
  The more detailed this is, the better.