# default prompt for all math benchmarks (e.g. gsm8k, math)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: ""

user: |-
  You are an advanced mathematical reasoning assistant. Your task is to analyze a given mathematical solution and count occurrences of three reasoning patterns. 
  **Base your analysis on context and logical intent, not just keywords.**

  The final answer should be in the following format:
  Self-Checking	\boxed{{X}}
  Self-Correction \boxed{{Y}}
  Trial-and-Error	\boxed{{Z}}

  ### **Reasoning Categories**:

  1. **Self-Checking**: When the author verifies a step, checks a calculation, or confirms whether the approach satisfies given conditions.  
    - **Typical phrases**:  
      - "Wait, let me check..."  
      - "Let’s verify if this works..."  
      - "Before going further, let’s confirm..."  
      - "Now, let's check if this satisfies the given conditions."

  2. **Self-Correction**: When the author identifies an error and actively corrects it.  
    - **Typical phrases**:  
      - "Oh! I see the mistake..."  
      - "Wait, that seems incorrect..."  
      - "Let me recompute this..."  
      - "Maybe I made an error, let me fix that."

  3. **Trial-and-Error Thinking**: When the author experiments with different approaches, tests values, or adjusts methods.  
    - **Typical phrases**:  
      - "Let’s try plugging in..."  
      - "What if we try another approach?"  
      - "Maybe this method works better..."  
      - "Let’s test a few cases before proceeding."

  **⚠ Important:** Do not rely solely on keyword matching. Consider the **logical intent** behind each sentence to classify it correctly.


  {examples}{problem}


  Please share your thinking process now. Remember: your goal is to write your thinking process as you approach this math problem. Note that we are not that much interested in the final solution, but much more in the process that lead you to it. 
  Did you have references to other problems you solved before in your mind? Write that down. Did you ponder upon which approach to take before doing derivations? Write that down. Does your current approach look too complicated and you need to try something else? 
  Say that and write down any alternative ideas you have. Did you notice that something doesn't look good and you need to double check previous derivations for mistake? That's what we are looking for - write that down and correct the solution, but don't erase the mistake! 
  The more detailed this is, the better.